export function getStatusPluginPostSource(hookPathname: string): string[] {
  // Why derived, not passed: the spool record needs the hook source and the
  // pathname already encodes it (`/hook/opencode`, `/hook/mimo-code`).
  const spoolSource = hookPathname === '/hook/mimo-code' ? 'mimo-code' : 'opencode'
  return [
    'async function post(hookEventName, extraProperties) {',
    '  // Why: resolve coords per post — the endpoint file may have been',
    '  // rewritten by a newer Orca since the last call. Pane/tab/worktree IDs',
    '  // stay on process.env because they are per-PTY (stable for the life of',
    '  // the OpenCode process), not per-Orca-instance.',
    '  const coords = resolveHookCoords();',
    '  const paneKey = process.env.ORCA_PANE_KEY;',
    '  if (!coords.port || !coords.token || !paneKey) return false;',
    `  const url = \`http://127.0.0.1:\${coords.port}${hookPathname}\`;`,
    '  const body = JSON.stringify({',
    '    paneKey,',
    '    launchToken: process.env.ORCA_AGENT_LAUNCH_TOKEN || "",',
    '    tabId: process.env.ORCA_TAB_ID || "",',
    '    worktreeId: process.env.ORCA_WORKTREE_ID || "",',
    '    env: coords.env,',
    '    version: coords.version,',
    '    payload: { hook_event_name: hookEventName, ...(extraProperties || {}) },',
    '  });',
    '  const controller = new AbortController();',
    '  const timeout = setTimeout(() => controller.abort(), HOOK_POST_TIMEOUT_MS);',
    '  if (timeout.unref) timeout.unref();',
    '  try {',
    '    const response = await fetch(url, {',
    '      method: "POST",',
    '      headers: {',
    '        "Content-Type": "application/json",',
    '        "X-Orca-Agent-Hook-Token": coords.token,',
    '      },',
    '      body,',
    '      signal: controller.signal,',
    '    });',
    '    return response.ok;',
    '  } catch {',
    '    // Why spool on transport failure: inside a docker sandbox the',
    '    // loopback POST can never route (bridge network), so without this',
    '    // the status event dies here. The spool dir is mounted into the',
    '    // sandbox and orcad drains it into the same store.',
    `    spoolHookEvent(${JSON.stringify(spoolSource)}, hookEventName, extraProperties, coords);`,
    '    // Why: OpenCode session events must never fail the agent run just',
    '    // because Orca is unavailable or the local loopback request failed.',
    '    return false;',
    '  } finally {',
    '    clearTimeout(timeout);',
    '  }',
    '}',
    '',
    '// Why the shell-hook spool shape: orcad replays these records through',
    '// buildSpoolHookBody, so the fields must match what the POSIX hooks write.',
    'function spoolHookEvent(source, hookEventName, extraProperties, coords) {',
    '  try {',
    '    const endpointPath = process.env.ORCA_AGENT_HOOK_ENDPOINT;',
    '    const paneKey = process.env.ORCA_PANE_KEY;',
    '    if (!endpointPath || !paneKey) return;',
    '    const fs = require("fs");',
    '    const path = require("path");',
    '    try { fs.accessSync(endpointPath, fs.constants.R_OK); } catch { return; }',
    '    const record = {',
    '      paneKey,',
    '      tabId: process.env.ORCA_TAB_ID || "",',
    '      worktreeId: process.env.ORCA_WORKTREE_ID || "",',
    '      env: (coords && coords.env) || "",',
    '      version: (coords && coords.version) || "",',
    '      launchToken: process.env.ORCA_AGENT_LAUNCH_TOKEN || "",',
    '      hookEventName,',
    '      source,',
    '      receivedAt: Date.now(),',
    '      payload: { hook_event_name: hookEventName, ...(extraProperties || {}) },',
    '    };',
    '    const spoolDir = path.join(path.dirname(endpointPath), "spool");',
    '    try { fs.mkdirSync(spoolDir, { recursive: true, mode: 0o700 }); } catch {}',
    '    const safeId = String(paneKey).slice(-36).replace(/[\\/:]/g, "_");',
    '    fs.appendFileSync(',
    '      path.join(spoolDir, "pane-" + safeId + ".jsonl"),',
    '      "\\n" + JSON.stringify(record) + "\\n"',
    '    );',
    '  } catch {}',
    '}'
  ]
}
